typography_spectrum: 0.1028022
color:
  saturation: 0.563711
  lightness: 0.414303
  brandStrength: 0.3596669
  rhythmicContrast: 0.8282841
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.3543461
name: BadPOTUS
title: Good Things To Learn
description: from Bad Presidents
