layout_spectrum: 0.8381541835201332
typography_spectrum: 0.05351552122115794
color:
  saturation: 0.7786293308165773
  lightness: 0.7618135862595559
  brandStrength: 0.7431918481079917
  rhythmicContrast: 0.3640038918389358
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
github: true
author:
  name: Mark Trudinger
  email: mark@trudinger.com
  url: 'http://thegrid.ai/badpotus/'
name: BadPOTUS
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1cd9a4d1-d031-497c-b353-03f84f4ba21b.ico
title: Bad President?
content: []
description: Good things we learn from Bad Presidents
purpose:
  - type: internal
    label: Then
    item: ecfcdcd1-935d-4844-98d9-63944a6df25d
  - type: internal
    label: '& Now'
    item: cc633c39-0b04-4f36-a5d8-01b74b3f1bf5
