layout_spectrum: 0.837288157596428
typography_spectrum: 0.10661477694831936
color:
  saturation: 0.33831289023695754
  lightness: 0.9214202393323995
  brandStrength: 0.6914435570308993
  rhythmicContrast: 0.0603305854215886
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
github: true
author:
  name: Mark Trudinger
  email: mark@trudinger.com
  url: 'http://thegrid.ai/badpotus/'
name: BadPOTUS
navigation:
  - name: One
    id: 544df794-e8ea-4fb2-ac3d-44e57e63c7dd
    type: content
  - name: Two
    id: b1b4f111-56db-424c-81a5-b3da0f7f37d1
    type: content
  - name: Three
    id: d196782b-968b-46d2-ad09-fe2c9f0163b4
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1cd9a4d1-d031-497c-b353-03f84f4ba21b.ico
title: Bad President?
content: []
description: Good things we learn from Bad Presidents
purpose:
  - type: internal
    label: Then
    item: ecfcdcd1-935d-4844-98d9-63944a6df25d
  - type: internal
    label: '& Now'
    item: cc633c39-0b04-4f36-a5d8-01b74b3f1bf5
