typography_spectrum: 0.966723490066476
color:
  saturation: 0.7748973242023794
  lightness: 0.7638080631229694
  brandStrength: 0.7413524011805617
  rhythmicContrast: 0.3648172566394257
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
github: true
layout_spectrum: 0.7011926805854102
author:
  name: Mark Trudinger
  email: mark@trudinger.com
  url: 'http://thegrid.ai/badpotus/'
name: BadPOTUS
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1cd9a4d1-d031-497c-b353-03f84f4ba21b.ico
title: Bad POTUS
content: []
description: ''
purpose:
  - type: internal
    label: Then
    item: ecfcdcd1-935d-4844-98d9-63944a6df25d
  - type: internal
    label: Again
    item: cc633c39-0b04-4f36-a5d8-01b74b3f1bf5
